//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebApp.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_student
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter your name")]
        public string Fname { get; set; }
  
        [EmailAddress(ErrorMessage = "Invalid email address")]  
        public string Email { get; set; }
        [MinLength(11,ErrorMessage ="Enter a valid Mobile number")]
        public string Mobile { get; set; }
        public string Description { get; set; }
    }
}
